org: brandolc18
service: api-diagramas

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 512
  timeout: 30
  role: arn:aws:iam::248056481657:role/LabRole
  environment:
    STAGE: ${opt:stage, 'dev'}

functions:
  generarDiagrama:
    handler: handler.generar_diagrama
    layers:
      - arn:aws:lambda:us-east-1:077246666028:layer:GraphvizLayer:1
    events:
      - http:
          path: /generar-diagrama
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
      - http:
          path: /generar-diagrama
          method: options
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  preflightHandler:
    handler: handler.preflight_handler
    events:
      - http:
          path: /generar-diagrama
          method: options

layers:
  graphviz:
    name: ${self:service}-graphviz-layer-${opt:stage, 'dev'}
    description: Capa con Graphviz y dependencias para generar diagramas
    compatibleRuntimes:
      - python3.9
    package:
      artifact: layers/graphviz-layer/graphviz-layer.zip
